### ISSUE TITLE
Version 0.0.14 nicht über pip

### ISSUE THREAD

**Issue by cybcon** [nerrixDE/DSBApi#23]
Der Versuch die Version 0.0.14 über pip zu installieren schlägt leider fehl.

Auf h[ttps://pypi.org/project/dsbapipy/](https://pypi.org/project/dsbapipy/) gibt es auch nur Version 0.0.13

```
pip install --upgrade --force-reinstall "dsbapipy>=0.0.14"

ERROR: Could not find a version that satisfies the requirement dsbapipy>=0.0.14 (from versions: 0.0.1, 0.0.2, 0.0.3, 0.0.4, 0.0.5, 0.0.6, 0.0.7, 0.0.8, 0.0.9, 0.0.10, 0.0.11, 0.0.13)
ERROR: No matching distribution found for dsbapipy>=0.0.14
```

**Comment by Joezi79** [comment]
Hallo Cybon,

kannst Du das bitte fixen. Ich nutze deine Library in Home Assistant. Dort bin ich darauf angewiesen, dass die Bibliothek über PIP gezogen werden kann. Vielen Dank vorab!

**Comment by cybcon** [comment]
Hallo Joezi79,
Nein, ich kann leider nicht den Pip Account von nerrixDE fixen.

Kannst Du nicht den genannten Workaround in Home Assistant nutzen?

Viele Grüße,
Cybcon

**Comment by Joezi79** [comment]
Den Workaround kann ich leider nicht nutzen. Ich muss bei Home Assistant / App Daemon die DBSApi Library als python package angeben. Dann wird es über PIP gezogen. Man kann bei AppDaemon auch init_commands angeben, dort habe ich es mit dem Workaround versucht, leider vergeblich. Ich werde mir was anderes einfallen lassen müssen.

![image](https://user-images.githubusercontent.com/38499550/138261555-087c21d7-aa23-42b5-be97-ccb139637245.png)

**Comment by Tobias-Auer** [comment]
> Ja, mein PIP Konto ist irgendwie kaputt. In der Zwichenzeit kannst du folgenden Befehl nutzen:
> 
> ```
> pip3 install https://github.com/nerrixDE/DSBApi/archive/refs/heads/master.zip
> ```

Ich habe diesen Befehl ausprobiert, weil bei mir der normale pip Befehl immer noch die alte Version installiert, bekomme aber leider folgenden Fehler:
```
Collecting https://github.com/nerrixDE/DSBApi/archive/refs/heads/master.zip
  Using cached https://github.com/nerrixDE/DSBApi/archive/refs/heads/master.zip
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [23 lines of output]
      Traceback (most recent call last):
        File "C:\Users\tobias\AppData\Roaming\Python\Python311\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Users\tobias\AppData\Roaming\Python\Python311\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\tobias\AppData\Roaming\Python\Python311\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\tobias\AppData\Local\Temp\pip-build-env-wmmj33i2\overlay\Lib\site-packages\setuptools\build_meta.py", line 325, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\tobias\AppData\Local\Temp\pip-build-env-wmmj33i2\overlay\Lib\site-packages\setuptools\build_meta.py", line 295, in _get_build_requires
          self.run_setup()
        File "C:\Users\tobias\AppData\Local\Temp\pip-build-env-wmmj33i2\overlay\Lib\site-packages\setuptools\build_meta.py", line 480, in run_setup
          super(_BuildMetaLegacyBackend, self).run_setup(setup_script=setup_script)
        File "C:\Users\tobias\AppData\Local\Temp\pip-build-env-wmmj33i2\overlay\Lib\site-packages\setuptools\build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 4, in <module>
        File "C:\Program Files\Python311\Lib\encodings\cp1252.py", line 23, in decode
          return codecs.charmap_decode(input,self.errors,decoding_table)[0]
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      UnicodeDecodeError: 'charmap' codec can't decode byte 0x8f in position 19: character maps to <undefined>
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```



Kein Plan, ob dieses Projekt überhaupt noch aktiven Support hat, wäre schade wenn nicht, denn diese library hat so viel Potenzial, wenn sie doch richtig zu installieren wäre. :(
